### PR TITLE
fix: add jdk11 profile

### PR DESCRIPTION
**Pull request by caalador**
Project can now be built with jdk11

### CODE REVIEW

**Review by mcollovati — APPROVED** [review]
I have failures when running tests with java 11 due to missing of jaxb, but compilation works fine.
Perhaps fixing test configuration can be done in a separate PR

**Comment by caalador** [comment]
The test running is might be more problematic as pluto comes with Tomcat8, but I guess Tomcat9 is jkd11 compatible?

**Comment by mcollovati** [comment]
Not sure that upgrading to Tomcat9 will solve the issue with jaxb, since in JDK 11 `jaxa.xml.bind` module has been removed, if I rememeber correctly, and I'm not sure that tomcat brings the jars on its own . 
TomEE may work, but I don't know if it is an easy stuff to deploy Pluto on a different container.

**Comment by mcollovati** [comment]
As a really dirty alternative, we can copy needed dependency with `maven-dependency-plugin` into `target/pluto-x.y.z/lib/` after unpacking the bundle, in `autosetup` profile.

**Pull request merged**
