### PR TITLE
Liferay 7.2.x+ compatibility changes

### PR DESCRIPTION
**Pull request by bbmarkus**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/portlet/183)

### CODE REVIEW

**Comment by caalador** [comment]
Made a merge master to feature branch PR so the actual changes for the review are easier to see.
Mind having a quick look that nothing went wrong with the merge https://github.com/vaadin/portlet/pull/184

**Review by caalador — COMMENTED** [review]
> Reviewed 4 of 4 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/vaadin/portlet/183)* status: 5 of 26 files reviewed, 13 unresolved discussions (waiting on @bbmarkus)

___
*[vaadin-portlet/pom.xml, line 45 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUsNddExabGKeeN9QB:-MMUsNddExabGKeeN9QC:b-oelnmi) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/pom.xml#L45)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         
> ```
</details>

Commented out dependency should be removed.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 40 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9Liv4IhkPdWLjsEM:-MMV9Liv4IhkPdWLjsEN:b-q2dmfm) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L40)):*
> ```
>     private static final String PORTLET_SCRIPTS_HASH = PORTLET_SCRIPTS + "-hash";
> ```
` PORTLET_SCRIPT_HASH = PORTLET_SCRIPT`
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV-WqkDPUsDo45Q3At:-MMV-WqkDPUsDo45Q3Au:b-1srwip) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L64)):*
> ```Java
> 
>             byte[] portletScript = getPortletScript(request).getBytes(StandardCharsets.UTF_8);
>             File htmlRoot = new File(getPublicHtmlPath());
> ```

Do we need to write files? couldn't we just store the hash and use that?  As the file contents is the same as we already have on the classpath and we can fail just because we can't write. Also now any old hash files will be left as they are not cleaned up.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVBV8Q89-K0HRLOn_Z:-MMVBV8Q89-K0HRLOn__:bo6zerm) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L64)):*
> ```
> File htmlRoot = new File(getPublicHtmlPath());
> ```
`File htmlRoot = new File(PropsUtil.get(PropsKeys.LIFERAY_WEB_PORTAL_DIR));` as the `html/VAADIN/...` can be reused
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 72 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVAEkp38NbvljVT6HE:-MMVAEkq5ilhINvWGHra:bfsbvov) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L72)):*
> ```Java
>             if (!portletMethodsFile.exists()) {
>                 if (!htmlRoot.canWrite())
>                     throw new IOException("Unable to write PortletMethods.js to Vaadin resosources directory");
> ```

In this instance we should not fail, but inline the script contents. It could be a bit more data to transfer, but it wouldn't fail horribly.

Also missing braces. Formatting should be done as per [Code conventions](https://github.com/vaadin/flow/tree/master/eclipse)
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 75 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVBzxQ6rbhVXeS6ADY:-MMVBzxQ6rbhVXeS6ADZ:b7ywrop) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L75)):*
> ```
>                 if (!vaadinAssets.isDirectory())
>                     vaadinAssets.mkdirs();
> ```
 ```
                 if (!vaadinAssets.isDirectory()) {
                     vaadinAssets.mkdirs();
                 }
 ```
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 83 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVAQwKA7gDUOa81VSQ:-MMVAQwKA7gDUOa81VSR:b-l8ssvn) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L83)):*
> ```Java
>             // What we probably want to do if this approach sticks around is to check if this has already been injected
>             if (!response.isCommitted()) {
>                 String scriptSrc = portletMethodsFile.getPath().replace(PropsUtil.get(PropsKeys.LIFERAY_WEB_PORTAL_DIR), "");
> ```

`String scriptSrc =  String.format("html/VAADIN/PortletMethods.%s.js", getPortletScriptsHash(request, portletScript));`
Also the src file should be built so that the same string is used for portletMethodsFile.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 97 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV99D9E75Ume6P5Jpy:-MMV99DACfGfhzasPm2_:b-29k2dn) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L97)):*
> ```
> private String getPortletScriptsHash(RenderRequest req, byte[] portletScripts) {
> ```
`private String getPortletScriptHash(RenderRequest req, byte[] portletScript) {`
to keep it aligned with the other name changes.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 98 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9mqnBCOcl8rqaS0f:-MMV9mqnBCOcl8rqaS0g:bd6acbr) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L98)):*
> ```Java
> 
>     private String getPortletScriptsHash(RenderRequest req, byte[] portletScripts) {
>         String scriptHash = (String) req.getPortletContext()
> ```

Shouldn't we always calculate the hash for portletScripts and compare that to the possible one in the context.
Also if the hash will always be checked against a file on the system then we should not even need to store it as an attribute.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 90 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9ZeXEw__9z7Cbo-n:-MMV9ZeXEw__9z7Cbo-o:b-cfmbvj) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L90)):*
> ```
> PORTLET_SCRIPTS
> ```
`PORTLET_SCRIPT` to have it hatch the method name change.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 155 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVDLbQBBV49WdVpq9B:-MMVDLbRDBifTORrceO5:bvbdlcm) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L155)):*
> ```Java
>      */
>     @PreserveOnRefresh
>     @Push(PushMode.DISABLED)
> ```

Is there something with liferay that makes push not work?
___
*[vaadin-portlet/src/main/resources/scripts/PortletMethods.js, line 19 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUx7m004L9YaMKcw-J:-MMUx7m004L9YaMKcw-K:b-jahi3r) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/resources/scripts/PortletMethods.js#L19)):*
> ```
> waitForHub 
> ```
`executeWhenHubIdle` would be a bit more descriptive.
___
*[vaadin-portlet/src/main/resources/scripts/PortletMethods.js, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUtajO6Ym1u4N_g2CC:-MMUtajO6Ym1u4N_g2CD:b5sb3cc) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/resources/scripts/PortletMethods.js#L64)):*
> ```JavaScript
>     window.Vaadin.Flow.Portlets.registerElement = function (tag, portletRegistryName, windowStates, portletModes, actionUrl) {
>         // <liferay>
>         // Force objects, urls and arrays for liferay portlet data to enable hub registration and hub usage
> ```

This whole part is a [liferay bug](https://issues.liferay.com/browse/LPS-107438)  that could be passed by using @PortletConfiguration annotation or adding the dependency to portlet.xml 
Our issue with this is that we would want to have it programmatically handled.

**Review by bbmarkus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/portlet/183)* status: 1 of 26 files reviewed, 13 unresolved discussions (waiting on @bbmarkus and @caalador)

___
*[vaadin-portlet/pom.xml, line 45 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUsNddExabGKeeN9QB:-MMZQF9GAIpINkrFSx-c:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/pom.xml#L45)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
>         
> ```
Commented out dependency should be removed.
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 40 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9Liv4IhkPdWLjsEM:-MMZQIFEBAepRjoonRgv:ba3dfob) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L40)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
>     private static final String PORTLET_SCRIPTS_HASH = PORTLET_SCRIPTS + "-hash";
> ```
` PORTLET_SCRIPT_HASH = PORTLET_SCRIPT`
</blockquote></details>

Removed
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVBV8Q89-K0HRLOn_Z:-MMZQKkp5FUAR-HZH74M:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> File htmlRoot = new File(getPublicHtmlPath());
> ```
`File htmlRoot = new File(PropsUtil.get(PropsKeys.LIFERAY_WEB_PORTAL_DIR));` as the `html/VAADIN/...` can be reused
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 72 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVAEkp38NbvljVT6HE:-MMZQLxH5d9G5QJ6veKe:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L72)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

In this instance we should not fail, but inline the script contents. It could be a bit more data to transfer, but it wouldn't fail horribly.

Also missing braces. Formatting should be done as per [Code conventions](https://github.com/vaadin/flow/tree/master/eclipse)
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 75 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVBzxQ6rbhVXeS6ADY:-MMZRWL91AANy668rou5:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L75)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
>                 if (!vaadinAssets.isDirectory())
>                     vaadinAssets.mkdirs();
> ```
 ```
                 if (!vaadinAssets.isDirectory()) {
                     vaadinAssets.mkdirs();
                 }
 ```
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 83 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVAQwKA7gDUOa81VSQ:-MMZNhBn7g5ZxfXwkrDC:b-zfcc4e) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L83)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

`String scriptSrc =  String.format("html/VAADIN/PortletMethods.%s.js", getPortletScriptsHash(request, portletScript));`
Also the src file should be built so that the same string is used for portletMethodsFile.

</blockquote></details>

Done, with slight refactoring
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 97 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV99D9E75Ume6P5Jpy:-MMZNd8cC3qqj7XEs194:bruxu49) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L97)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> private String getPortletScriptsHash(RenderRequest req, byte[] portletScripts) {
> ```
`private String getPortletScriptHash(RenderRequest req, byte[] portletScript) {`
to keep it aligned with the other name changes.
</blockquote></details>

The method is removed.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 98 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9mqnBCOcl8rqaS0f:-MMZNm1J3KhMQ_pn1P7T:bd9mog5) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L98)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Shouldn't we always calculate the hash for portletScripts and compare that to the possible one in the context.
Also if the hash will always be checked against a file on the system then we should not even need to store it as an attribute.
</blockquote></details>

Won't be saved in the context anymore, the only reason the hash is there is to not have to write the file on every request and still have it up to date on changes. Changed it to use vaadin-portlet version number for non-snapshot versions.

This is hardly ideal, but it is better than having Liferay inline the script, because the processing it does is interesting (particularly when using MARKUP_HEAD_ELEMENT, which I also decided to get rid of because of how Liferay may navigate between pages).

The portlet methods script could probably be part of the same bundle where you get the other client side js from, since it isn't dynamic, but I decided not to do that change for now because I assume there is or was a reason why it isn't so to begin with?
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 90 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9ZeXEw__9z7Cbo-n:-MMZN_oUA6rpJ2_Vv3rR:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L90)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> PORTLET_SCRIPTS
> ```
`PORTLET_SCRIPT` to have it hatch the method name change.
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 155 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVDLbQBBV49WdVpq9B:-MMZLG8Q49k0vEvyHoQZ:bdzb8om) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L155)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is there something with liferay that makes push not work?
</blockquote></details>

Considering Atmosphere complains about not being able to initialize websockets when you deploy to Liferay that is indeed the assumption I made here.

Also testing push set to e.g. automatic does indeed confirm that it will probably not work. Also, on a separate note the static bundle in the addressbook demo project is not set up to even have the expected script/s (and I was basically told not to spend much time on websockets, since I have only 1 week to work with).
___
*[vaadin-portlet/src/main/resources/scripts/PortletMethods.js, line 19 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUx7m004L9YaMKcw-J:-MMZNXn85Te_vClxfpTG:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/resources/scripts/PortletMethods.js#L19)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> waitForHub 
> ```
`executeWhenHubIdle` would be a bit more descriptive.
</blockquote></details>

Done.
___
*[vaadin-portlet/src/main/resources/scripts/PortletMethods.js, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUtajO6Ym1u4N_g2CC:-MMZPOjTDv_-FyK2Tf_v:b1y4bvw) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/resources/scripts/PortletMethods.js#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This whole part is a [liferay bug](https://issues.liferay.com/browse/LPS-107438)  that could be passed by using @PortletConfiguration annotation or adding the dependency to portlet.xml 
Our issue with this is that we would want to have it programmatically handled.
</blockquote></details>

I know, but the renderData checking being absent in 7.3 is a bug all on its own, because that bit is only needed for 7.3.

Out of curiously what is wrong with the xml anyway? I can see wanting to avoid the annotation, but portlet authors will edit the xml anyway for name etc. so the dependency needing to be there seems like a rather minor thing.

**Review by caalador — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 7 files at r2, 5 of 6 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 4 of 7 files at r8, 1 of 2 files at r10, 1 of 3 files at r11, 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/vaadin/portlet/183)* status: all files reviewed, 4 unresolved discussions (waiting on @bbmarkus)

___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 98 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9mqnBCOcl8rqaS0f:-MMnZMSx9GK4mFB7NjR9:b-sfk0x4) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L98)):*
<details><summary><i>Previously, bbmarkus (Markus Willman) wrote…</i></summary><blockquote>

Won't be saved in the context anymore, the only reason the hash is there is to not have to write the file on every request and still have it up to date on changes. Changed it to use vaadin-portlet version number for non-snapshot versions.

This is hardly ideal, but it is better than having Liferay inline the script, because the processing it does is interesting (particularly when using MARKUP_HEAD_ELEMENT, which I also decided to get rid of because of how Liferay may navigate between pages).

The portlet methods script could probably be part of the same bundle where you get the other client side js from, since it isn't dynamic, but I decided not to do that change for now because I assume there is or was a reason why it isn't so to begin with?
</blockquote></details>


Actually I think it is just that it was forgotten at the time as there were many other problems with the portlets.

It would actually be a good idea to mode it from `src/resources/scripts`  to `src/resources/META-INF/resources/scripts` as then it will be served by the servlet container on a request to `/scripts/PortletMethods.js`
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 155 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMVDLbQBBV49WdVpq9B:-MMn_Dn-AAOb6YxNUhdD:bb6mt9b) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L155)):*
<details><summary><i>Previously, bbmarkus (Markus Willman) wrote…</i></summary><blockquote>

Considering Atmosphere complains about not being able to initialize websockets when you deploy to Liferay that is indeed the assumption I made here.

Also testing push set to e.g. automatic does indeed confirm that it will probably not work. Also, on a separate note the static bundle in the addressbook demo project is not set up to even have the expected script/s (and I was basically told not to spend much time on websockets, since I have only 1 week to work with).
</blockquote></details>

:+1:
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 248 at r15](https://reviewable.io/reviews/vaadin/portlet/183#-MMn_Vhd22XlpnZXwDfe:-MMn_VheAKBzVh12SaSA:b-n2sy4s) ([raw file](https://github.com/vaadin/portlet/blob/770536fe24561087d9b00f4e7a15d9af8c61f0d9/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L248)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         // How do we get this to only exec once for multiple portlets on same
>         // page, but still every time the page refreshes?
>         String initScript = "<script type=\"text/javascript\">\n"
>                 + getPortletScript(request) + "\n</script>";
> ```
</details>

As you can note here it wasn't fixed to the end and moving it to the servlet static file location makes us be able to have it as not inlined and just give it the file to load. If you end up moving it then we could get this fixed here also.
___
*[vaadin-portlet/src/main/resources/scripts/PortletMethods.js, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMUtajO6Ym1u4N_g2CC:-MMnaclw11LoHck8U9zd:b-vog4zj) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/resources/scripts/PortletMethods.js#L64)):*
<details><summary><i>Previously, bbmarkus (Markus Willman) wrote…</i></summary><blockquote>

I know, but the renderData checking being absent in 7.3 is a bug all on its own, because that bit is only needed for 7.3.

Out of curiously what is wrong with the xml anyway? I can see wanting to avoid the annotation, but portlet authors will edit the xml anyway for name etc. so the dependency needing to be there seems like a rather minor thing.
</blockquote></details>

It's more that it should work according to the specification.

Portlet 3.0 would allow defining it fully with annotations, also we are trying to activate 3.0 programmatically if it is available for the page the portlet is on (which is the problem for liferay) or then "fallback" on 2.x specification (at least we did in the beginning).

**Review by bbmarkus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/portlet/183)* status: 23 of 26 files reviewed, 4 unresolved discussions (waiting on @bbmarkus and @caalador)

___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 64 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV-WqkDPUsDo45Q3At:-MMsvq4v5yTFDadKVhqw:b-gary9w) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Do we need to write files? couldn't we just store the hash and use that?  As the file contents is the same as we already have on the classpath and we can fail just because we can't write. Also now any old hash files will be left as they are not cleaned up.
</blockquote></details>

Done, or rather files are no longer written
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java, line 98 at r14](https://reviewable.io/reviews/vaadin/portlet/183#-MMV9mqnBCOcl8rqaS0f:-MMsvcIB0UnAt6QohBC1:b-osplpo) ([raw file](https://github.com/vaadin/portlet/blob/20ef001af70a12cd48fd5e7a4e6cfc9fec7ec532/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinLiferayPortlet.java#L98)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>


Actually I think it is just that it was forgotten at the time as there were many other problems with the portlets.

It would actually be a good idea to mode it from `src/resources/scripts`  to `src/resources/META-INF/resources/scripts` as then it will be served by the servlet container on a request to `/scripts/PortletMethods.js`
</blockquote></details>

Done, you could end up using either the vaadin-portlet-static.war or the portlet context path to serve it (I opted for the static bundle here, as seems more friendly to caches).
___
*[vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java, line 248 at r15](https://reviewable.io/reviews/vaadin/portlet/183#-MMn_Vhd22XlpnZXwDfe:-MMsw6jZ8PaG2H30J_Hb:b-896fix) ([raw file](https://github.com/vaadin/portlet/blob/770536fe24561087d9b00f4e7a15d9af8c61f0d9/vaadin-portlet/src/main/java/com/vaadin/flow/portal/VaadinPortlet.java#L248)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
>         // How do we get this to only exec once for multiple portlets on same
>         // page, but still every time the page refreshes?
>         String initScript = "<script type=\"text/javascript\">\n"
>                 + getPortletScript(request) + "\n</script>";
> ```
As you can note here it wasn't fixed to the end and moving it to the servlet static file location makes us be able to have it as not inlined and just give it the file to load. If you end up moving it then we could get this fixed here also.
</blockquote></details>

Done.

**Review by caalador — COMMENTED** [review]
Failing tests:
```
 IPCEventIT.sendEventFromSourceToTarget[ANY_Chrome_] 	
 IPCEventIT.sendEventFromSourceToTarget_portletsOnDifferentTabsReceiveEventsIndependently[ANY_Chrome_] 	
 IPCNotVaadinEventIT.sendEventFromNonVaadinToVaadin[ANY_Chrome_] 	
 IPCNotVaadinEventIT.sendEventFromVaadinToNonVaadin[ANY_Chrome_]
 HubRenderIT.changeModeAndState_modeAndStateAreKept[ANY_Chrome_]
```

At least 2 of the test screenshots had NPE
```
[08:57:09]	[Step 2/3] [WARNING] [talledLocalContainer] [http-nio-8080-exec-9] ERROR com.vaadin.flow.portal.DefaultPortletErrorHandler - java.lang.NullPointerException
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] java.lang.NullPointerException
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.portal.events.EventSourceView.lambda$new$c2950344$1(EventSourceView.java:31)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:441)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:441)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
[08:57:09]	[Step 2/3] [INFO] [talledLocalContainer] 	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:409)
```

> Reviewed 2 of 3 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/vaadin/portlet/183#-:-MMt3aNYEG4cRoRqUgHb:brm32n5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by caalador** [comment]
[Misc_Portlet_Validation_build_341.zip](https://github.com/vaadin/portlet/files/5587988/Misc_Portlet_Validation_build_341.zip)

**Pull request closed without merging**
